version: '3'
services:
  server:
    volumes:
      - ./config.py:/fed-flow/app/config/config.py
      - ./../../../Graphs(testbed):/Graphs
      - ./../../../agent:/app/agent
    image: negaranabestani/fed-flow:rabbitmq
    ports:
      - "5002:5002"
    hostname: server
    deploy:
      resources:
        limits:
          cpus: '6'
        reservations:
          cpus: '6'
      restart_policy:
        condition: on-failure
    working_dir: /fed-flow/app/rl_training/runner
    entrypoint: bash -c "python3 /fed-flow/app/rl_training/runner/rl_server_runner.py -o True -s edge_based_rl_splitting -e True"

  client1:
    volumes:
      - ./config.py:/fed-flow/app/config/config.py
    image: docker-reg.ir/fed-flow:rabbitmq
    hostname: client1
    deploy:
      resources:
        limits:
          cpus: '2'
        reservations:
          cpus: '2'
      restart_policy:
        condition: on-failure
    working_dir: /fed-flow/app/rl_training/runner
    entrypoint: bash -c "python3 /fed-flow/energy/service.py & python3 /fed-flow/app/rl_training/runner/rl_client_runner.py -i 0 -o True -s random_splitting -e True & wait -n"