version: '3'
services:
  server:
    build:
      context: .
      dockerfile: server.Dockerfile
    ports:
      - "51008:51008"
    hostname: server
    entrypoint: bash -c "python3 /fed-flow/app/fl_training/runner/fed_server_run.py -o True -s no_edge_rl_splitting"
  client1:
    build:
      context: .
      dockerfile: client.Dockerfile
      args:
        - INDEX=0
    hostname: client1
    entrypoint: bash -c "python3 /fed-flow/app/fl_training/runner/fed_client_run.py -i 0 -o True -s no_edge_rl_splitting"

  client2:
    build:
      context: .
      dockerfile: client.Dockerfile
      args:
        - INDEX=1
    hostname: client2
    entrypoint: bash -c "python3 /fed-flow/app/fl_training/runner/fed_client_run.py -i 1 -o True -s no_edge_rl_splitting"

  client3:
    build:
      context: .
      dockerfile: client.Dockerfile
      args:
        - INDEX=2
    hostname: client3
    entrypoint: bash -c "python3 /fed-flow/app/fl_training/runner/fed_client_run.py -i 2 -o True -s no_edge_rl_splitting"

  client4:
    build:
      context: .
      dockerfile: client.Dockerfile
      args:
        - INDEX=3
    hostname: client4
    entrypoint: bash -c "python3 /fed-flow/app/fl_training/runner/fed_client_run.py -i 3 -o True -s no_edge_rl_splitting"

  client5:
    build:
      context: .
      dockerfile: client.Dockerfile
      args:
        - INDEX=4
    hostname: client5
    entrypoint: bash -c "python3 /fed-flow/app/fl_training/runner/fed_client_run.py -i 4 -o True -s no_edge_rl_splitting"
