version: '3'
services:
  server:
    volumes:
      - ./config.py:/fed-flow/app/config/config.py
      - ./../../../Graphs:/Graphs
      - ./../../../agent:/app/agent
    image: negaranabestani/fed-flow:rabbitmq
    ports:
      - "5002:5002"
    hostname: server
    deploy:
      restart_policy:
        condition: on-failure
    working_dir: /fed-flow/app/rl_training/runner
    entrypoint: bash -c "python3 /fed-flow/app/rl_training/runner/rl_server_runner.py -o True -s edge_based_rl_splitting -e True"