version: '3'
services:
  server:
    deploy:
      resources:
        reservations:
          cpus: "3"
          memory: "1000M"
    image: fed-flow:test
    restart: always
    ports:
      - "5002:5002"
    hostname: server
    volumes:
      - /home/little-wolf:/Graphs
    working_dir: /fed-flow/app/rl_training/runner
    entrypoint: bash -c "python3 /fed-flow/app/rl_training/runner/rl_server_runner.py -o True -s edge_based_rl_splitting -e True"

  edge1:
    deploy:
      resources:
        reservations:
          cpus: "2"
          memory: "500M"
    image: fed-flow:test
    restart: always
    ports:
      - "5001:5001"
    hostname: edge1
    working_dir: /fed-flow/app/rl_training/runner
    depends_on:
      - server
    entrypoint: bash -c "python3 /fed-flow/app/rl_training/runner/rl_edgeserver_runner.py -i 0 -o True -s edge_based_rl_splitting -e True"

  client1:
    deploy:
      resources:
        reservations:
          cpus: "1"
          memory: "250M"
    image: fed-flow:test
    restart: always
    hostname: client1
    working_dir: /fed-flow/app/rl_training/runner
    depends_on:
      - edge1
    entrypoint: bash -c "python3 /fed-flow/app/rl_training/runner/rl_client_runner.py -i 0 -o True -s edge_based_rl_splitting -e True"