version: '3'
services:
  server:
    volumes:
      - ./config.py:/fed-flow/app/config/config.py
      - ./Graphs:/Graphs
      - ./agent:/app/agent
    image: negaranabestani/fed-flow:rabbitmq
    ports:
      - "51008:51008"
    hostname: server
    deploy:
      resources:
        limits:
          cpus: '2'
        reservations:
          cpus: '2'
      restart_policy:
        condition: on-failure
    working_dir: /fed-flow/app/fl_training/runner
    entrypoint: bash -c "python3 /fed-flow/app/fl_training/runner/fed_server_run.py -o True -s random_splitting -e True"

  broker:
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    image: rabbitmq:3.13-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    hostname: broker

  edge1:
    volumes:
      - ./config.py:/fed-flow/app/config/config.py
    image: negaranabestani/fed-flow:rabbitmq
    ports:
      - "5001:5001"
    hostname: edge1
    deploy:
      resources:
        limits:
          cpus: '1.5'
        reservations:
          cpus: '1.5'
      restart_policy:
        condition: on-failure
    working_dir: /fed-flow/app/fl_training/runner
    depends_on:
      - server
    entrypoint: bash -c "python3 /fed-flow/app/fl_training/runner/fed_edgeserver_run.py -i 0 -o True -s random_splitting -e True & python3 /fed-flow/energy/service.py & wait -n"

  client1:
    deploy:
      resources:
        limits:
          cpus: '0.5'
        reservations:
          cpus: '0.5'
      restart_policy:
        condition: on-failure
    volumes:
      - ./config.py:/fed-flow/app/config/config.py
    image: negaranabestani/fed-flow:rabbitmq
    hostname: client1
    working_dir: /fed-flow/app/fl_training/runner
    depends_on:
      - edge1
    entrypoint: bash -c "python3 /fed-flow/app/fl_training/runner/fed_client_run.py -i 0 -o True -s random_splitting -e True & python3 /fed-flow/energy/service.py & wait -n"