version: '3'
services:
  server:
    image: fed-flow:test
    ports:
      - "51008:51008"
    hostname: server
    restart: always
    working_dir: /fed-flow/app/fl_training/runner
    entrypoint: bash -c "python3 /fed-flow/app/fl_training/runner/fed_server_run.py"
  client1:
    image: fed-flow:test
    depends_on:
      - server
    hostname: client1
    restart: always
    working_dir: /fed-flow/app/fl_training/runner
    entrypoint: bash -c "python3 /fed-flow/app/fl_training/runner/fed_client_run.py -i 0"
  client2:
    image: fed-flow:test
    depends_on:
      - server
    hostname: client2
    restart: always
    working_dir: /fed-flow/app/fl_training/runner
    entrypoint: bash -c "python3 /fed-flow/app/fl_training/runner/fed_client_run.py -i 1"
  client3:
    image: fed-flow:test
    depends_on:
      - server
    hostname: client3
    restart: always
    working_dir: /fed-flow/app/fl_training/runner
    entrypoint: bash -c "python3 /fed-flow/app/fl_training/runner/fed_client_run.py -i 2"

  client4:
    image: fed-flow:test
    depends_on:
      - server
    hostname: client4
    restart: always
    working_dir: /fed-flow/app/fl_training/runner
    entrypoint: bash -c "python3 /fed-flow/app/fl_training/runner/fed_client_run.py -i 3"