services:
    broker:
        image: rabbitmq:3-management
        network_mode: host
        volumes:
          - rabbitmq_data:/var/lib/rabbitmq
        environment:
          RABBITMQ_DEFAULT_USER: rabbitmq
          RABBITMQ_DEFAULT_PASS: rabbitmq
          RABBITMQ_MAX_MESSAGE_SIZE: 536870912
        healthcheck:
          test: [ "CMD", "rabbitmq-diagnostics", "-q", "ping" ]
          interval: 30s
          timeout: 30s
          retries: 3

volumes:
  rabbitmq_data:
