version: '3'
services:
  server:
    build:
      context: ../../../
      dockerfile: server.Dockerfile
    ports:
      - "51008:51008"
    hostname: server
  client1:
    build:
      context: ../../../
      dockerfile: client.Dockerfile
      args:
        - INDEX=0
    depends_on:
      - server
    hostname: client1
  client2:
    build:
      context: ../../../
      dockerfile: client.Dockerfile
      args:
        - INDEX=1
    depends_on:
      - server
    hostname: client2
  client3:
    build:
      context: ../../../
      dockerfile: client.Dockerfile
      args:
        - INDEX=2
    depends_on:
      - server
    hostname: client3
