version: '3'
services:
  server:
    build:
      context: ../../../
      dockerfile: server.Dockerfile
    ports:
      - "5004:5004"
    hostname: server
    entrypoint: bash -c "python3 /fed-flow/app/fl_training/runner/fed_server_run.py -o True -s fake_splitting"

  edge1:
    build:
      context: ../../../
      dockerfile: edge.Dockerfile
      args:
        - INDEX=0
    ports:
      - "5001:5001"
    hostname: edge1
    depends_on:
      - server
    entrypoint: bash -c "python3 /fed-flow/app/fl_training/runner/fed_edgeserver_run.py -i 0 -o True -s fake_splitting"

  client1:
    build:
      context: ../../../
      dockerfile: client.Dockerfile
      args:
        - INDEX=0
    hostname: client1
    depends_on:
      - edge1
    entrypoint: bash -c "python3 /fed-flow/app/fl_training/runner/fed_client_run.py -i 0 -o True -s fake_splitting"

  client2:
    build:
      context: ../../../
      dockerfile: client.Dockerfile
      args:
        - INDEX=1
    hostname: client2
    depends_on:
      - edge1
    entrypoint: bash -c "python3 /fed-flow/app/fl_training/runner/fed_client_run.py -i 1 -o True -s fake_splitting"

  edge2:
    build:
      context: ../../../
      dockerfile: edge.Dockerfile
      args:
        - INDEX=0
    ports:
      - "5005:5005"
    hostname: edge2
    depends_on:
      - server
    entrypoint: bash -c "python3 /fed-flow/app/fl_training/runner/fed_edgeserver_run.py -i 1 -o True -s fake_splitting"

  client3:
    build:
      context: ../../../
      dockerfile: client.Dockerfile
      args:
        - INDEX=2
    hostname: client3
    depends_on:
      - edge2
    entrypoint: bash -c "python3 /fed-flow/app/fl_training/runner/fed_client_run.py -i 2 -o True -s fake_splitting"

  client4:
    build:
      context: ../../../
      dockerfile: client.Dockerfile
      args:
        - INDEX=3
    hostname: client4
    depends_on:
      - edge2
    entrypoint: bash -c "python3 /fed-flow/app/fl_training/runner/fed_client_run.py -i 3 -o True -s fake_splitting"

