version: '3'
services:
  server:
    image: fed-flow:test
    hostname: server
    restart: always
    ports:
      - "51008:51008"
    working_dir: /fed-flow/app/fl_training/runner
    entrypoint: bash -c "python3 /fed-flow/app/fl_training/runner/fed_server_run.py"
  client1:
    image: fed-flow:test
    hostname: client1
    restart: always
    working_dir: /fed-flow/app/fl_training/runner
    entrypoint: bash -c "python3 /fed-flow/app/fl_training/runner/fed_client_run.py -i 0"

