version: '3'
services:
  server:
    build:
      context: ../../../
      dockerfile: server.Dockerfile
    ports:
      - "5008:5008"
  client1:
    build:
      context: ../../../
      dockerfile: client.Dockerfile
      args:
        - INDEX=0
    depends_on:
      - server
  client2:
    build:
      context: ../../../
      dockerfile: client.Dockerfile
      args:
        - INDEX=1
    depends_on:
      - server
  client3:
    build:
      context: ../../../
      dockerfile: client.Dockerfile
      args:
        - INDEX=2
    depends_on:
      - server
#  client4:
#    build:
#      context: ../../../
#      dockerfile: client.Dockerfile
#      args:
#        - INDEX=3
#    depends_on:
#      - server
#  client5:
#    build:
#      context: ../../../
#      dockerfile: client.Dockerfile
#      args:
#        - INDEX=4
#    depends_on:
#      - server
