version: '3'
services:
  server:
    image: fed-flow:test
    ports:
      - "5002:5002"
    restart: always
    working_dir: /fed-flow/app/fl_training/runner
    hostname: server
    entrypoint: bash -c "python3 /fed-flow/app/fl_training/runner/fed_server_run.py -o True -s random_splitting -e True"

  edge1:
    image: fed-flow:test
    ports:
      - "5001:5001"
    restart: always
    working_dir: /fed-flow/app/fl_training/runner
    hostname: edge1
    depends_on:
      - server
    entrypoint: bash -c "python3 /fed-flow/app/fl_training/runner/fed_edgeserver_run.py -i 0 -o True -s random_splitting -e True"
  client1:
    image: fed-flow:test
    restart: always
    working_dir: /fed-flow/app/fl_training/runner
    hostname: client1
    depends_on:
      - edge1
    entrypoint: bash -c "python3 /fed-flow/app/fl_training/runner/fed_client_run.py -i 0 -o True -s random_splitting -e True"

