services:
  server:
    volumes:
      - ./config.py:/fed-flow/app/config/config.py
      - ./../../../Graphs:/fed-flow/Graphs
      - ./../../../app/logs:/fed-flow/app/logs
    image: autlpdslab/fedflow:rabbitmq
    ports:
      - "5002:5002"
    hostname: server
    deploy:
      resources:
        limits:
          cpus: '1'
        reservations:
          cpus: '1'
      restart_policy:
        condition: on-failure
    working_dir: /fed-flow/app/fl_training/runner
    depends_on:
      - broker
    entrypoint: bash -c "python3 /fed-flow/app/fl_training/runner/fed_server_run.py -o True -s fake_splitting -e True "

  broker:
    image: rabbitmq:3.13-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    hostname: broker

  edge1:
    volumes:
      - ./config.py:/fed-flow/app/config/config.py
    image: autlpdslab/fedflow:rabbitmq
    labels:
        com.docker-tc.enabled: "1"     # Enables Traffic Control mangement
        com.docker-tc.limit: "0.5mbps"  # Setting the bandwidth limit to 25mbit
    ports:
      - "5001:5001"
    hostname: edge1
    deploy:
      resources:
        limits:
          cpus: '1'
        reservations:
          cpus: '1'
      restart_policy:
        condition: on-failure
    working_dir: /fed-flow/app/fl_training/runner
    depends_on:
      - server
      - broker
    entrypoint: bash -c "python3 /fed-flow/app/fl_training/runner/fed_edgeserver_run.py -o True -s fake_splitting -e True & python3 /fed-flow/energy/service.py & wait -n"

  client1:
    volumes:
      - ./config.py:/fed-flow/app/config/config.py
    image: autlpdslab/fedflow:rabbitmq
    labels:
      com.docker-tc.enabled: "1"     # Enables Traffic Control mangement
      com.docker-tc.limit: "0.5mbps"  # Setting the bandwidth limit to 25mbit
    hostname: client1
    deploy:
      resources:
        limits:
          cpus: '1.0'
        reservations:
          cpus: '1.0'
      restart_policy:
        condition: on-failure
    working_dir: /fed-flow/app/fl_training/runner
    depends_on:
      - server
      - broker
      - edge1
    entrypoint: bash -c "python3 /fed-flow/energy/service.py & python3 /fed-flow/app/fl_training/runner/fed_client_run.py -i 0 -o True -sb True -s fake_splitting -en True -e True & wait -n"

  client2:
    volumes:
      - ./config.py:/fed-flow/app/config/config.py
    image: autlpdslab/fedflow:rabbitmq
    labels:
      com.docker-tc.enabled: "1"     # Enables Traffic Control mangement
      com.docker-tc.limit: "0.5mbps"  # Setting the bandwidth limit to 25mbit
    hostname: client2
    deploy:
      resources:
        limits:
          cpus: '1.0'
        reservations:
          cpus: '1.0'
      restart_policy:
        condition: on-failure
    working_dir: /fed-flow/app/fl_training/runner
    depends_on:
      - server
      - broker
      - edge1
    entrypoint: bash -c "python3 /fed-flow/energy/service.py & python3 /fed-flow/app/fl_training/runner/fed_client_run.py -i 1 -o True -sb True -s fake_splitting -en True -e True & wait -n"

  client3:
    volumes:
      - ./config.py:/fed-flow/app/config/config.py
      - ./econfig1.py:/fed-flow/energy/config.py
    image: autlpdslab/fedflow:rabbitmq
    labels:
      com.docker-tc.enabled: "1"     # Enables Traffic Control mangement
      com.docker-tc.limit: "0.5mbps"  # Setting the bandwidth limit to 25mbit
    hostname: client3
    deploy:
      resources:
        limits:
          cpus: '1.0'
        reservations:
          cpus: '1.0'
      restart_policy:
        condition: on-failure
    working_dir: /fed-flow/app/fl_training/runner
    depends_on:
      - server
      - broker
      - edge1
    entrypoint: bash -c "python3 /fed-flow/energy/service.py & python3 /fed-flow/app/fl_training/runner/fed_client_run.py -i 2 -o True -sb True -s fake_splitting -en True -e True & wait -n"
