version: '3.9'
services:
  server:
    volumes:
      - ./config.py:/fed-flow/app/config/config.py
    image: negaranabestani/fed-flow:rabbitmq
    ports:
      - "5002:5002"
    hostname: server
    deploy:
      restart_policy:
        condition: on-failure
    working_dir: /fed-flow/app/fl_training/runner
    entrypoint: bash -c "python3 /fed-flow/app/fl_training/runner/fed_server_run.py -o True -s fake_splitting -e True"
  broker:
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    attach: false
    image: rabbitmq:3.13-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    hostname: broker
  edge1:
    volumes:
      - ./config.py:/fed-flow/app/config/config.py
    image: negaranabestani/fed-flow:rabbitmq
    ports:
      - "5001:5001"
    hostname: edge1
    deploy:
      restart_policy:
        condition: on-failure
    working_dir: /fed-flow/app/fl_training/runner
    depends_on:
      - server
    entrypoint: bash -c "python3 /fed-flow/app/fl_training/runner/fed_edgeserver_run.py -i 0 -o True -s fake_splitting"
  client1:
    volumes:
      - ./config.py:/fed-flow/app/config/config.py
    image: negaranabestani/fed-flow:rabbitmq
    hostname: client1
    deploy:
      restart_policy:
        condition: on-failure
    working_dir: /fed-flow/app/fl_training/runner
    depends_on:
      - edge1
    entrypoint: bash -c "python3 /fed-flow/app/fl_training/runner/fed_client_run.py -i 0 -o True -s fake_splitting -e True & python3 /fed-flow/energy/service.py & wait -n"

  client2:
    attach: false
    volumes:
      - ./config.py:/fed-flow/app/config/config.py
    image: negaranabestani/fed-flow:rabbitmq
    hostname: client2
    deploy:
      restart_policy:
        condition: on-failure
    working_dir: /fed-flow/app/fl_training/runner
    depends_on:
      - edge1
    entrypoint: bash -c "python3 /fed-flow/app/fl_training/runner/fed_client_run.py -i 1 -o True -s fake_splitting -e True & python3 /fed-flow/energy/service.py & wait -n"

  client3:
    attach: false
    volumes:
      - ./config.py:/fed-flow/app/config/config.py
    image: negaranabestani/fed-flow:rabbitmq
    hostname: client3
    deploy:
      restart_policy:
        condition: on-failure
    working_dir: /fed-flow/app/fl_training/runner
    depends_on:
      - edge1
    entrypoint: bash -c "python3 /fed-flow/app/fl_training/runner/fed_client_run.py -i 2 -o True -s fake_splitting -e True & python3 /fed-flow/energy/service.py & wait -n"
