version: '3'
services:
  server:
    image: fed-flow:test
    ports:
      - "5004:5004"
    restart: always
    working_dir: /fed-flow/app/fl_training/runner
    hostname: server
    entrypoint: bash -c "python3 /fed-flow/app/fl_training/runner/fed_server_run.py -o True -s fake_splitting -e True"

  edge1:
    image: fed-flow:test
    ports:
      - "5001:5001"
    restart: always
    working_dir: /fed-flow/app/fl_training/runner
    hostname: edge1
    depends_on:
      - server
    entrypoint: bash -c "python3 /fed-flow/app/fl_training/runner/fed_edgeserver_run.py -i 0 -o True -s fake_splitting -e True"

  client1:
    image: fed-flow:test
    restart: always
    working_dir: /fed-flow/app/fl_training/runner
    hostname: client1
    depends_on:
      - edge1
    entrypoint: bash -c "python3 /fed-flow/app/fl_training/runner/fed_client_run.py -i 0 -o True -s fake_splitting -e True & python3 /fed-flow/energy/service.py & wait -n"

  client2:
    image: fed-flow:test
    restart: always
    working_dir: /fed-flow/app/fl_training/runner
    hostname: client2
    depends_on:
      - edge1
    entrypoint: bash -c "python3 /fed-flow/app/fl_training/runner/fed_client_run.py -i 1 -o True -s fake_splitting -e True & python3 /fed-flow/energy/service.py & wait -n"

  edge2:
    image: fed-flow:test
    ports:
      - "5005:5005"
    restart: always
    working_dir: /fed-flow/app/fl_training/runner
    hostname: edge2
    depends_on:
      - server
    entrypoint: bash -c "python3 /fed-flow/app/fl_training/runner/fed_edgeserver_run.py -i 1 -o True -s fake_splitting -e True"

  client3:
    image: fed-flow:test
    restart: always
    working_dir: /fed-flow/app/fl_training/runner
    hostname: client3
    depends_on:
      - edge2
    entrypoint: bash -c "python3 /fed-flow/app/fl_training/runner/fed_client_run.py -i 2 -o True -s fake_splitting -e True & python3 /fed-flow/energy/service.py & wait -n"

  client4:
    image: fed-flow:test
    restart: always
    working_dir: /fed-flow/app/fl_training/runner
    hostname: client4
    depends_on:
      - edge2
    entrypoint: bash -c "python3 /fed-flow/app/fl_training/runner/fed_client_run.py -i 3 -o True -s fake_splitting -e True & python3 /fed-flow/energy/service.py & wait -n"

