version: '3'
services:
  server:
    build:
      context: ../../../
      dockerfile: server.Dockerfile
    ports:
      - "5008:5008"
    entrypoint: bash -c "python3 /fed-flow/app/fl_training/runner/fed_server_run.py -o True -s fake_splitting"

  edge1:
    build:
      context: ../../../
      dockerfile: edge.Dockerfile
      args:
        - INDEX=0
    entrypoint: bash -c "python3 /fed-flow/app/fl_training/runner/fed_edgeserver_run.py -i 0 -o True -s fake_splitting"
  client1:
    build:
      context: ../../../
      dockerfile: client.Dockerfile
      args:
        - INDEX=0
    entrypoint: bash -c "python3 /fed-flow/app/fl_training/runner/fed_client_run.py -i 0 -o True -s fake_splitting"

