version: '3'
services:
  server:
    image: fed-flow:test
    deploy:
      resources:
        limits:
          cpus: '3'
        reservations:
          cpus: '3'
      restart_policy:
        condition: on-failure
    ports:
      - "5002:5002"
    hostname: server
    working_dir: /fed-flow/app/rl_training/runner
    entrypoint: bash -c "python3 /fed-flow/app/rl_training/runner/rl_server_runner.py -o True -s edge_based_rl_splitting -e True"
    volumes:
      - ./../../../Graphs:/Graphs

  edge1:
    image: fed-flow:test
    deploy:
      resources:
        limits:
          cpus: '2'
        reservations:
          cpus: '2'
      restart_policy:
        condition: on-failure
    ports:
      - "5001:5001"
    hostname: edge1
    working_dir: /fed-flow/app/rl_training/runner
    depends_on:
      - server
    entrypoint: bash -c "python3 /fed-flow/app/rl_training/runner/rl_edgeserver_runner.py -i 0 -o True -s edge_based_rl_splitting -e True"

  client1:
    image: fed-flow:test
    deploy:
      resources:
        limits:
          cpus: '0.5'
        reservations:
          cpus: '0.5'
      restart_policy:
        condition: on-failure
    hostname: client1
    working_dir: /fed-flow/app/rl_training/runner
    depends_on:
      - edge1
    entrypoint: bash -c "python3 /fed-flow/app/rl_training/runner/rl_client_runner.py -i 0 -o True -s edge_based_rl_splitting -e True"