version: '3'
services:
  server:
    build:
      context: ../../../
      dockerfile: server.Dockerfile
    ports:
      - "5008:5008"
  client1:
    build:
      context: ../../../
      dockerfile: client.Dockerfile
