version: '3'
services:
  server:
    volumes:
      - ./config.py:/fed-flow/app/config/config.py
      - ./../../../Graphs:/Graphs
      - ./../../../agent:/app/agent
    image: docker-reg.ir/fed-flow:rabbitmq
    ports:
      - "5002:5002"
    hostname: server
    depends_on:
      - broker
    deploy:
      restart_policy:
        condition: on-failure
    working_dir: /fed-flow/app/rl_training/runner
    entrypoint: bash -c "python3 /fed-flow/app/rl_training/runner/rl_server_runner.py -o True -s edge_based_rl_splitting -e True"
  broker:
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    image: rabbitmq:3.13-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    hostname: broker

  edge1:
    volumes:
      - ./config.py:/fed-flow/app/config/config.py
    image: docker-reg.ir/fed-flow:rabbitmq
    ports:
      - "5001:5001"
    hostname: edge1
    deploy:
      restart_policy:
        condition: on-failure
    working_dir: /fed-flow/app/rl_training/runner
    depends_on:
      - server
      - broker
    entrypoint: bash -c "python3 /fed-flow/app/rl_training/runner/rl_edgeserver_runner.py -o True -i 0 -s edge_based_rl_splitting -e True"
  client1:
    volumes:
      - ./config.py:/fed-flow/app/config/config.py
    image: docker-reg.ir/fed-flow:rabbitmq
    hostname: client1
    deploy:
      restart_policy:
        condition: on-failure
    working_dir: /fed-flow/app/rl_training/runner
    depends_on:
      - edge1
      - broker
    entrypoint: bash -c "python3 /fed-flow/energy/service.py & python3 /fed-flow/app/rl_training/runner/rl_client_runner.py -i 0 -o True -s edge_based_rl_splitting -e True & wait -n"