version: '3'
services:
  server:
    image: fed-flow:test
    ports:
      - "5002:5002"
    hostname: server
    restart: always
    working_dir: /fed-flow/app/fl_training/runner
    entrypoint: bash -c "python3 /fed-flow/app/fl_training/runner/fed_server_run.py -o True -s fake_splitting -e True"

  edge1:
    image: fed-flow:test
    ports:
      - "5001:5001"
    hostname: edge1
    restart: always
    working_dir: /fed-flow/app/fl_training/runner
    depends_on:
      - server
    entrypoint: bash -c "python3 /fed-flow/app/fl_training/runner/fed_edgeserver_run.py -i 0 -o True -s fake_splitting -e True"
  client1:
    image: fed-flow:test
    hostname: client1
    restart: always
    working_dir: /fed-flow/app/fl_training/runner
    depends_on:
      - edge1
    entrypoint: bash -c "python3 /fed-flow/app/fl_training/runner/fed_client_run.py -i 0 -o True -s fake_splitting -e True"

  client2:
    image: fed-flow:test
    hostname: client2
    restart: always
    working_dir: /fed-flow/app/fl_training/runner
    depends_on:
      - edge1
    entrypoint: bash -c "python3 /fed-flow/app/fl_training/runner/fed_client_run.py -i 1 -o True -s fake_splitting -e True"

  client3:
    image: fed-flow:test
    hostname: client3
    restart: always
    working_dir: /fed-flow/app/fl_training/runner
    depends_on:
      - edge1
    entrypoint: bash -c "python3 /fed-flow/app/fl_training/runner/fed_client_run.py -i 2 -o True -s fake_splitting -e True"

