version: '3.9'
services:
  server:
    volumes:
      - ./config.py:/fed-flow/app/config/config.py
    image: negaranabestani/fed-flow:rabbitmq
    pull_policy: never
    ports:
      - "51008:51008"
    deploy:
#      resources:
#        limits:
#          cpus: '3'
#        reservations:
#          cpus: '3'
      restart_policy:
        condition: on-failure
    working_dir: /fed-flow/app/fl_training/runner
    hostname: server
    entrypoint: bash -c "python3 /fed-flow/app/fl_training/runner/fed_server_run.py -o True -s no_edge_fake_splitting"

  broker:
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    attach: false
    image: rabbitmq:3.13-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    hostname: broker
  client1:
    attach: false
    volumes:
      - ./config.py:/fed-flow/app/config/config.py
    image: negaranabestani/fed-flow:rabbitmq
    deploy:
#      resources:
#        limits:
#          cpus: '0.5'
#        reservations:
#          cpus: '0.5'
      restart_policy:
        condition: on-failure
    working_dir: /fed-flow/app/fl_training/runner
    hostname: client1
    entrypoint: bash -c "python3 /fed-flow/energy/service.py & python3 /fed-flow/app/fl_training/runner/fed_client_run.py -i 0 -o True -s no_edge_fake_splitting & wait -n"

  client2:
    attach: false
    volumes:
      - ./config.py:/fed-flow/app/config/config.py
    image: negaranabestani/fed-flow:rabbitmq
    deploy:
#      resources:
#        limits:
#          cpus: '0.5'
#        reservations:
#          cpus: '0.5'
      restart_policy:
        condition: on-failure
    working_dir: /fed-flow/app/fl_training/runner
    hostname: client2
    entrypoint: bash -c "python3 /fed-flow/energy/service.py & python3 /fed-flow/app/fl_training/runner/fed_client_run.py -i 1 -o True -s no_edge_fake_splitting & wait -n"

  client3:
    attach: false
    volumes:
      - ./config.py:/fed-flow/app/config/config.py
    image: negaranabestani/fed-flow:rabbitmq

    deploy:
#      resources:
#        limits:
#          cpus: '0.5'
#        reservations:
#          cpus: '0.5'
      restart_policy:
        condition: on-failure
    working_dir: /fed-flow/app/fl_training/runner
    hostname: client3
    entrypoint: bash -c "python3 /fed-flow/energy/service.py & python3 /fed-flow/app/fl_training/runner/fed_client_run.py -i 2 -o True -s no_edge_fake_splitting & wait -n"