services:
  node_base: &node_base
    image: autlpdslab/fedflow:latest
    working_dir: /fed-flow
    depends_on:
      broker:
        condition: service_healthy
    environment:
      AGGREGATION: "fedavg"
      DECENTRALIZED: "True"
      D2D: "False"
      MOBILITY: "True"
      CLUSTERING: "none_clustering"
      OFFLOADING: "False"
      SPLITTING_METHOD: "none_spliting"
      MODEL: "VGG"
      DATASET: "cifar10"
      NODE_INDEX: "0"
      IP: "0.0.0.0"
      PORT: "8080"
      RABBITMQ_URL: "amqp://rabbitmq:rabbitmq@broker:5672/"
      NEIGHBORS: ""
      NODE_TYPE: ""
      ROUND_COUNT: ""
      DEVICE_COUNT: ""
      COORDINATES: "0.0,0.0,0.0"
    entrypoint: >
      bash -c "python3 /fed-flow/main.py
      --aggregation $$AGGREGATION
      --decentralized $$DECENTRALIZED
      --d2d $$D2D
      --mobility $$MOBILITY
      --clustering $$CLUSTERING
      -o $$OFFLOADING
      -s $$SPLITTING_METHOD
      --model $$MODEL
      --dataset $$DATASET
      --index $$NODE_INDEX
      --ip $$IP
      --port $$PORT
      --rabbitmq-url $$RABBITMQ_URL
      --neighbors $$NEIGHBORS
      --node-type $$NODE_TYPE
      --coordinates $$COORDINATES"
    volumes:
      - ./Results:/fed-flow/test_app/decentralized_test/mobility_test/neighbor_selection/Results
      - ./data:/fed-flow/app/dataset/data
      - ./processed_data/012/012_data.csv:/fed-flow/app/dataset/mobility_data/data.csv
      - ./config.py:/fed-flow/app/config/config.py

  client1:
    <<: *node_base
    environment:
      AGGREGATION: "fedavg"
      DECENTRALIZED: "True"
      D2D: "False"
      MOBILITY: "True"
      CLUSTERING: "none_clustering"
      OFFLOADING: "True"
      SPLITTING_METHOD: "fake_decentralized_splitting"
      MODEL: "VGG"
      DATASET: "cifar10"
      NODE_INDEX: "0"
      IP: "client1"
      PORT: "8080"
      RABBITMQ_URL: "amqp://rabbitmq:rabbitmq@broker:5672/client1"
      NEIGHBORS: "edge1,8081 edge2,8083"
      NODE_TYPE: "client"
      ROUND_COUNT: "10"
      DEVICE_COUNT: "2"
      COORDINATES: "20.0,20.0,5.0"
      SCENARIO_DESCRIPTION: "Centralized  1 1 Offloading"
    deploy:
      resources:
        limits:
          cpus: "8"
          memory: 1G

  client2:
    <<: *node_base
    environment:
      AGGREGATION: "fedavg"
      DECENTRALIZED: "True"
      D2D: "False"
      MOBILITY: "True"
      CLUSTERING: "none_clustering"
      OFFLOADING: "True"
      SPLITTING_METHOD: "fake_decentralized_splitting"
      MODEL: "VGG"
      DATASET: "cifar10"
      NODE_INDEX: "0"
      IP: "client2"
      PORT: "8082"
      RABBITMQ_URL: "amqp://rabbitmq:rabbitmq@broker:5672/client2"
      NEIGHBORS: "edge2,8083 edge1,8081"
      NODE_TYPE: "client"
      ROUND_COUNT: "10"
      DEVICE_COUNT: "2"
      COORDINATES: "20.0,20.0,5.0"
      SCENARIO_DESCRIPTION: "Centralized  1 1 Offloading"
    deploy:
      resources:
        limits:
          cpus: "8"
          memory: 1G

  edge1:
    <<: *node_base
    environment:
      AGGREGATION: "fedavg"
      DECENTRALIZED: "True"
      D2D: "False"
      MOBILITY: "True"
      CLUSTERING: "none_clustering"
      OFFLOADING: "True"
      SPLITTING_METHOD: "fake_decentralized_splitting"
      MODEL: "VGG"
      DATASET: "cifar10"
      NODE_INDEX: "0"
      IP: "edge1"
      PORT: "8081"
      RABBITMQ_URL: "amqp://rabbitmq:rabbitmq@broker:5672/edge1"
      NEIGHBORS: "client1,8080 client2,8082 edge2,8083"
      NODE_TYPE: "edge"
      ROUND_COUNT: "10"
      DEVICE_COUNT: "2"
      COORDINATES: "10.0,10.0,10.0"
      SCENARIO_DESCRIPTION: "Centralized  1 1 Offloading"
    deploy:
      resources:
        limits:
          cpus: "12"
          memory: 1G

  edge2:
    <<: *node_base
    environment:
      AGGREGATION: "fedavg"
      DECENTRALIZED: "True"
      D2D: "False"
      MOBILITY: "True"
      CLUSTERING: "none_clustering"
      OFFLOADING: "True"
      SPLITTING_METHOD: "fake_decentralized_splitting"
      MODEL: "VGG"
      DATASET: "cifar10"
      NODE_INDEX: "0"
      IP: "edge2"
      PORT: "8083"
      RABBITMQ_URL: "amqp://rabbitmq:rabbitmq@broker:5672/edge2"
      NEIGHBORS: "client2,8082 client1,8080 edge1,8081"
      NODE_TYPE: "edge"
      ROUND_COUNT: "10"
      DEVICE_COUNT: "2"
      COORDINATES: "10.0,20.0,50.0"
      SCENARIO_DESCRIPTION: "Centralized  1 1 Offloading"
    deploy:
      resources:
        limits:
          cpus: "12"
          memory: 1G



  
  broker:
    image: rabbitmq:3-management
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq
      RABBITMQ_MAX_MESSAGE_SIZE: 536870912
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "ping" ]
      interval: 30s
      timeout: 30s
      retries: 3

volumes:
  rabbitmq_data:
