services:
  node_base: &node_base
    image: autlpdslab/fedflow:latest
    working_dir: /fed-flow
    depends_on:
      broker:
        condition: service_healthy
    environment:
      AGGREGATION: "fedavg"
      DECENTRALIZED: "True"
      D2D: "False"
      MOBILITY: "True"
      CLUSTERING: "none_clustering"
      OFFLOADING: "False"
      SPLITTING_METHOD: "none_spliting"
      MODEL: "VGG"
      DATASET: "cifar10"
      NODE_INDEX: "0"
      IP: "0.0.0.0"
      PORT: "8080"
      RABBITMQ_URL: "amqp://rabbitmq:rabbitmq@broker:5672/"
      NEIGHBORS: ""
      NODE_TYPE: ""
      ROUND_COUNT: ""
      DEVICE_COUNT: ""
      COORDINATES: "0.0,0.0,0.0"
    entrypoint: >
      bash -c "python3 /fed-flow/main.py
      --aggregation $$AGGREGATION
      --decentralized $$DECENTRALIZED
      --d2d $$D2D
      --mobility $$MOBILITY
      --clustering $$CLUSTERING
      -o $$OFFLOADING
      -s $$SPLITTING_METHOD
      --model $$MODEL
      --dataset $$DATASET
      --index $$NODE_INDEX
      --ip $$IP
      --port $$PORT
      --rabbitmq-url $$RABBITMQ_URL
      --neighbors $$NEIGHBORS
      --node-type $$NODE_TYPE
      --coordinates $$COORDINATES"
    volumes:
      - ./Results:/fed-flow/Results
      - ./data:/fed-flow/app/dataset/data
      - ./config.py:/fed-flow/app/config/config.py

  client1:
    <<: *node_base
    environment:
      AGGREGATION: "fedavg"
      DECENTRALIZED: "True"
      D2D: "False"
      MOBILITY: "True"
      CLUSTERING: "none_clustering"
      OFFLOADING: "True"
      SPLITTING_METHOD: "fake_decentralized_splitting"
      MODEL: "VGG"
      DATASET: "cifar10"
      NODE_INDEX: "0"
      IP: "client1"
      PORT: "8080"
      RABBITMQ_URL: "amqp://rabbitmq:rabbitmq@broker:5672/client1"
      NEIGHBORS: "edge1,8081"
      NODE_TYPE: "client"
      ROUND_COUNT: "3"
      DEVICE_COUNT: "12"
      COORDINATES: "40.004176,116.326091,50.0"
      SCENARIO_DESCRIPTION: "Centralized  1 1 Offloading"
    deploy:
      resources:
        limits:
          cpus: "3"
          memory: 1G
    volumes:
       - ./processed_data/001/001_data.csv:/fed-flow/app/dataset/mobility_data/data.csv:ro
       - ./Results:/fed-flow/Results
       - ./data:/fed-flow/app/dataset/data
       - ./config.py:/fed-flow/app/config/config.py


  client2:
    <<: *node_base
    environment:
      AGGREGATION: "fedavg"
      DECENTRALIZED: "True"
      D2D: "False"
      MOBILITY: "True"
      CLUSTERING: "none_clustering"
      OFFLOADING: "True"
      SPLITTING_METHOD: "fake_decentralized_splitting"
      MODEL: "VGG"
      DATASET: "cifar10"
      NODE_INDEX: "0"
      IP: "client2"
      PORT: "8082"
      RABBITMQ_URL: "amqp://rabbitmq:rabbitmq@broker:5672/client2"
      NEIGHBORS: "edge1,8081"
      NODE_TYPE: "client"
      ROUND_COUNT: "3"
      DEVICE_COUNT: "12"
      COORDINATES: "40.004476,116.326291,50.0"
      SCENARIO_DESCRIPTION: "Centralized  1 1 Offloading"
    deploy:
      resources:
        limits:
          cpus: "3"
          memory: 1G
    volumes:
      - ./processed_data/001/001_data.csv:/fed-flow/app/dataset/mobility_data/data.csv:ro
      - ./Results:/fed-flow/Results
      - ./data:/fed-flow/app/dataset/data
      - ./config.py:/fed-flow/app/config/config.py

  client3:
    <<: *node_base
    environment:
      AGGREGATION: "fedavg"
      DECENTRALIZED: "True"
      D2D: "False"
      MOBILITY: "True"
      CLUSTERING: "none_clustering"
      OFFLOADING: "True"
      SPLITTING_METHOD: "fake_decentralized_splitting"
      MODEL: "VGG"
      DATASET: "cifar10"
      NODE_INDEX: "0"
      IP: "client3"
      PORT: "8084"
      RABBITMQ_URL: "amqp://rabbitmq:rabbitmq@broker:5672/client3"
      NEIGHBORS: "edge1,8081"
      NODE_TYPE: "client"
      ROUND_COUNT: "3"
      DEVICE_COUNT: "12"
      COORDINATES: "39.9970,116.3285,50.0"
      SCENARIO_DESCRIPTION: "Centralized  1 1 Offloading"
    deploy:
      resources:
        limits:
          cpus: "3"
          memory: 1G
    volumes:
      - ./processed_data/001/001_data.csv:/fed-flow/app/dataset/mobility_data/data.csv:ro
      - ./Results:/fed-flow/Results
      - ./data:/fed-flow/app/dataset/data
      - ./config.py:/fed-flow/app/config/config.py

  client4:
    <<: *node_base
    environment:
      AGGREGATION: "fedavg"
      DECENTRALIZED: "True"
      D2D: "False"
      MOBILITY: "True"
      CLUSTERING: "none_clustering"
      OFFLOADING: "True"
      SPLITTING_METHOD: "fake_decentralized_splitting"
      MODEL: "VGG"
      DATASET: "cifar10"
      NODE_INDEX: "0"
      IP: "client4"
      PORT: "8086"
      RABBITMQ_URL: "amqp://rabbitmq:rabbitmq@broker:5672/client4"
      NEIGHBORS: "edge2,8083"
      NODE_TYPE: "client"
      ROUND_COUNT: "3"
      DEVICE_COUNT: "12"
      COORDINATES: "39.979873,116.330951,50.0"
      SCENARIO_DESCRIPTION: "Centralized  1 1 Offloading"
    deploy:
      resources:
        limits:
          cpus: "3"
          memory: 1G
    volumes:
      - ./processed_data/008/008_data.csv:/fed-flow/app/dataset/mobility_data/data.csv:ro
      - ./Results:/fed-flow/Results
      - ./data:/fed-flow/app/dataset/data
      - ./config.py:/fed-flow/app/config/config.py

  client5:
    <<: *node_base
    environment:
      AGGREGATION: "fedavg"
      DECENTRALIZED: "True"
      D2D: "False"
      MOBILITY: "True"
      CLUSTERING: "none_clustering"
      OFFLOADING: "True"
      SPLITTING_METHOD: "fake_decentralized_splitting"
      MODEL: "VGG"
      DATASET: "cifar10"
      NODE_INDEX: "0"
      IP: "client5"
      PORT: "8088"
      RABBITMQ_URL: "amqp://rabbitmq:rabbitmq@broker:5672/client5"
      NEIGHBORS: "edge2,8083"
      NODE_TYPE: "client"
      ROUND_COUNT: "3"
      DEVICE_COUNT: "12"
      COORDINATES: "39.980173,116.331151,50.0"
      SCENARIO_DESCRIPTION: "Centralized  1 1 Offloading"
    deploy:
      resources:
        limits:
          cpus: "3"
          memory: 1G
    volumes:
      - ./processed_data/008/008_data.csv:/fed-flow/app/dataset/mobility_data/data.csv:ro
      - ./Results:/fed-flow/Results
      - ./data:/fed-flow/app/dataset/data
      - ./config.py:/fed-flow/app/config/config.py

  client6:
    <<: *node_base
    environment:
      AGGREGATION: "fedavg"
      DECENTRALIZED: "True"
      D2D: "False"
      MOBILITY: "True"
      CLUSTERING: "none_clustering"
      OFFLOADING: "True"
      SPLITTING_METHOD: "fake_decentralized_splitting"
      MODEL: "VGG"
      DATASET: "cifar10"
      NODE_INDEX: "0"
      IP: "client6"
      PORT: "8090"
      RABBITMQ_URL: "amqp://rabbitmq:rabbitmq@broker:5672/client6"
      NEIGHBORS: "edge2,8083"
      NODE_TYPE: "client"
      ROUND_COUNT: "3"
      DEVICE_COUNT: "12"
      COORDINATES: "39.979623,116.331051,50.0"
      SCENARIO_DESCRIPTION: "Centralized  1 1 Offloading"
    deploy:
      resources:
        limits:
          cpus: "3"
          memory: 1G
    volumes:
      - ./processed_data/008/008_data.csv:/fed-flow/app/dataset/mobility_data/data.csv:ro
      - ./Results:/fed-flow/Results
      - ./data:/fed-flow/app/dataset/data
      - ./config.py:/fed-flow/app/config/config.py

  client7:
    <<: *node_base
    environment:
      AGGREGATION: "fedavg"
      DECENTRALIZED: "True"
      D2D: "False"
      MOBILITY: "True"
      CLUSTERING: "none_clustering"
      OFFLOADING: "True"
      SPLITTING_METHOD: "fake_decentralized_splitting"
      MODEL: "VGG"
      DATASET: "cifar10"
      NODE_INDEX: "0"
      IP: "client7"
      PORT: "8092"
      RABBITMQ_URL: "amqp://rabbitmq:rabbitmq@broker:5672/client7"
      NEIGHBORS: "edge3,8085"
      NODE_TYPE: "client"
      ROUND_COUNT: "3"
      DEVICE_COUNT: "12"
      COORDINATES: "40.047500,116.298611,50.0"
      SCENARIO_DESCRIPTION: "Centralized  1 1 Offloading"
    deploy:
      resources:
        limits:
          cpus: "3"
          memory: 1G
    volumes:
      - ./processed_data/009/009_data.csv:/fed-flow/app/dataset/mobility_data/data.csv:ro
      - ./Results:/fed-flow/Results
      - ./data:/fed-flow/app/dataset/data
      - ./config.py:/fed-flow/app/config/config.py

  client8:
    <<: *node_base
    environment:
      AGGREGATION: "fedavg"
      DECENTRALIZED: "True"
      D2D: "False"
      MOBILITY: "True"
      CLUSTERING: "none_clustering"
      OFFLOADING: "True"
      SPLITTING_METHOD: "fake_decentralized_splitting"
      MODEL: "VGG"
      DATASET: "cifar10"
      NODE_INDEX: "0"
      IP: "client8"
      PORT: "8094"
      RABBITMQ_URL: "amqp://rabbitmq:rabbitmq@broker:5672/client8"
      NEIGHBORS: "edge3,8085"
      NODE_TYPE: "client"
      ROUND_COUNT: "3"
      DEVICE_COUNT: "12"
      COORDINATES: "40.047800,116.298811,50.0"
      SCENARIO_DESCRIPTION: "Centralized  1 1 Offloading"
    deploy:
      resources:
        limits:
          cpus: "3"
          memory: 1G
    volumes:
      - ./processed_data/009/009_data.csv:/fed-flow/app/dataset/mobility_data/data.csv:ro
      - ./Results:/fed-flow/Results
      - ./data:/fed-flow/app/dataset/data
      - ./config.py:/fed-flow/app/config/config.py

  client9:
    <<: *node_base
    environment:
      AGGREGATION: "fedavg"
      DECENTRALIZED: "True"
      D2D: "False"
      MOBILITY: "True"
      CLUSTERING: "none_clustering"
      OFFLOADING: "True"
      SPLITTING_METHOD: "fake_decentralized_splitting"
      MODEL: "VGG"
      DATASET: "cifar10"
      NODE_INDEX: "0"
      IP: "client3"
      PORT: "8096"
      RABBITMQ_URL: "amqp://rabbitmq:rabbitmq@broker:5672/client3"
      NEIGHBORS: "edge3,8085"
      NODE_TYPE: "client"
      ROUND_COUNT: "3"
      DEVICE_COUNT: "12"
      COORDINATES: "40.047250,116.298711,50.0"
      SCENARIO_DESCRIPTION: "Centralized  1 1 Offloading"
    deploy:
      resources:
        limits:
          cpus: "6"
          memory: 1G
    volumes:
      - ./processed_data/009/009_data.csv:/fed-flow/app/dataset/mobility_data/data.csv:ro
      - ./Results:/fed-flow/Results
      - ./data:/fed-flow/app/dataset/data
      - ./config.py:/fed-flow/app/config/config.py

  client10:
    <<: *node_base
    environment:
      AGGREGATION: "fedavg"
      DECENTRALIZED: "True"
      D2D: "False"
      MOBILITY: "True"
      CLUSTERING: "none_clustering"
      OFFLOADING: "True"
      SPLITTING_METHOD: "fake_decentralized_splitting"
      MODEL: "VGG"
      DATASET: "cifar10"
      NODE_INDEX: "0"
      IP: "client10"
      PORT: "8098"
      RABBITMQ_URL: "amqp://rabbitmq:rabbitmq@broker:5672/client10"
      NEIGHBORS: "edge4,8087"
      NODE_TYPE: "client"
      ROUND_COUNT: "3"
      DEVICE_COUNT: "12"
      COORDINATES: "39.983899,116.326083,50.0"
      SCENARIO_DESCRIPTION: "Centralized  1 1 Offloading"
    deploy:
      resources:
        limits:
          cpus: "3"
          memory: 1G
    volumes:
      - ./processed_data/012/012_data.csv:/fed-flow/app/dataset/mobility_data/data.csv:ro
      - ./Results:/fed-flow/Results
      - ./data:/fed-flow/app/dataset/data
      - ./config.py:/fed-flow/app/config/config.py

  client11:
    <<: *node_base
    environment:
      AGGREGATION: "fedavg"
      DECENTRALIZED: "True"
      D2D: "False"
      MOBILITY: "True"
      CLUSTERING: "none_clustering"
      OFFLOADING: "True"
      SPLITTING_METHOD: "fake_decentralized_splitting"
      MODEL: "VGG"
      DATASET: "cifar10"
      NODE_INDEX: "0"
      IP: "client11"
      PORT: "8100"
      RABBITMQ_URL: "amqp://rabbitmq:rabbitmq@broker:5672/client11"
      NEIGHBORS: "edge4,8087"
      NODE_TYPE: "client"
      ROUND_COUNT: "3"
      DEVICE_COUNT: "12"
      COORDINATES: "39.984199,116.326283,50.0"
      SCENARIO_DESCRIPTION: "Centralized  1 1 Offloading"
    deploy:
      resources:
        limits:
          cpus: "3"
          memory: 1G
    volumes:
      - ./processed_data/012/012_data.csv:/fed-flow/app/dataset/mobility_data/data.csv:ro
      - ./Results:/fed-flow/Results
      - ./data:/fed-flow/app/dataset/data
      - ./config.py:/fed-flow/app/config/config.py

  client12:
    <<: *node_base
    environment:
      AGGREGATION: "fedavg"
      DECENTRALIZED: "True"
      D2D: "False"
      MOBILITY: "True"
      CLUSTERING: "none_clustering"
      OFFLOADING: "True"
      SPLITTING_METHOD: "fake_decentralized_splitting"
      MODEL: "VGG"
      DATASET: "cifar10"
      NODE_INDEX: "0"
      IP: "client12"
      PORT: "8102"
      RABBITMQ_URL: "amqp://rabbitmq:rabbitmq@broker:5672/client12"
      NEIGHBORS: "edge4,8087"
      NODE_TYPE: "client"
      ROUND_COUNT: "3"
      DEVICE_COUNT: "12"
      COORDINATES: "39.983649,116.326183,50.0"
      SCENARIO_DESCRIPTION: "Centralized  1 1 Offloading"
    deploy:
      resources:
        limits:
          cpus: "3"
          memory: 1G
    volumes:
      - ./processed_data/012/012_data.csv:/fed-flow/app/dataset/mobility_data/data.csv:ro
      - ./Results:/fed-flow/Results
      - ./data:/fed-flow/app/dataset/data
      - ./config.py:/fed-flow/app/config/config.py



  edge1:
    <<: *node_base
    environment:
      AGGREGATION: "fedavg"
      DECENTRALIZED: "True"
      D2D: "False"
      MOBILITY: "True"
      CLUSTERING: "none_clustering"
      OFFLOADING: "True"
      SPLITTING_METHOD: "fake_decentralized_splitting"
      MODEL: "VGG"
      DATASET: "cifar10"
      NODE_INDEX: "0"
      IP: "edge1"
      PORT: "8081"
      RABBITMQ_URL: "amqp://rabbitmq:rabbitmq@broker:5672/edge1"
      NEIGHBORS: "edge2,8083,edge3,8085,edge4,8087"
      NODE_TYPE: "edge"
      ROUND_COUNT: "3"
      DEVICE_COUNT: "4"
      COORDINATES: "40.004176,116.328500,50"
      SCENARIO_DESCRIPTION: "Centralized  1 1 Offloading"
    deploy:
      resources:
        limits:
          cpus: "5"
          memory: 1G
    volumes:
      - ./Results:/fed-flow/Results
      - ./data:/fed-flow/app/dataset/data
      - ./config.py:/fed-flow/app/config/config.py


  edge2:
    <<: *node_base
    environment:
      AGGREGATION: "fedavg"
      DECENTRALIZED: "True"
      D2D: "False"
      MOBILITY: "True"
      CLUSTERING: "none_clustering"
      OFFLOADING: "True"
      SPLITTING_METHOD: "fake_decentralized_splitting"
      MODEL: "VGG"
      DATASET: "cifar10"
      NODE_INDEX: "0"
      IP: "edge2"
      PORT: "8083"
      RABBITMQ_URL: "amqp://rabbitmq:rabbitmq@broker:5672/edge2"
      NEIGHBORS: "edge1,8081,edge3,8085,edge4,8087"
      NODE_TYPE: "edge"
      ROUND_COUNT: "10"
      DEVICE_COUNT: "3"
      COORDINATES: "39.979873,116.327000,50"
      SCENARIO_DESCRIPTION: "Centralized  1 1 Offloading"
    deploy:
      resources:
        limits:
          cpus: "5"
          memory: 1G
    volumes:
      - ./Results:/fed-flow/Results
      - ./data:/fed-flow/app/dataset/data
      - ./config.py:/fed-flow/app/config/config.py

  edge3:
    <<: *node_base
    environment:
      AGGREGATION: "fedavg"
      DECENTRALIZED: "True"
      D2D: "False"
      MOBILITY: "True"
      CLUSTERING: "none_clustering"
      OFFLOADING: "True"
      SPLITTING_METHOD: "fake_decentralized_splitting"
      MODEL: "VGG"
      DATASET: "cifar10"
      NODE_INDEX: "0"
      IP: "edge3"
      PORT: "8085"
      RABBITMQ_URL: "amqp://rabbitmq:rabbitmq@broker:5672/edge3"
      NEIGHBORS: "edge1,8081,edge2,8083,edge4,8087"
      NODE_TYPE: "edge"
      ROUND_COUNT: "10"
      DEVICE_COUNT: "3"
      COORDINATES: "40.045000,116.304000,50"
      SCENARIO_DESCRIPTION: "Centralized  1 1 Offloading"
    deploy:
      resources:
        limits:
          cpus: "5"
          memory: 1G
    volumes:
      - ./Results:/fed-flow/Results
      - ./data:/fed-flow/app/dataset/data
      - ./config.py:/fed-flow/app/config/config.py

  edge4:
    <<: *node_base
    environment:
      AGGREGATION: "fedavg"
      DECENTRALIZED: "True"
      D2D: "False"
      MOBILITY: "True"
      CLUSTERING: "none_clustering"
      OFFLOADING: "True"
      SPLITTING_METHOD: "fake_decentralized_splitting"
      MODEL: "VGG"
      DATASET: "cifar10"
      NODE_INDEX: "0"
      IP: "edge4"
      PORT: "8087"
      RABBITMQ_URL: "amqp://rabbitmq:rabbitmq@broker:5672/edge4"
      NEIGHBORS: "edge1,8081,edge2,8083,edge3,8085"
      NODE_TYPE: "edge"
      ROUND_COUNT: "3"
      DEVICE_COUNT: "4"
      COORDINATES: "39.985500,116.322000,50"
      SCENARIO_DESCRIPTION: "Centralized  1 1 Offloading"
    deploy:
      resources:
        limits:
          cpus: "5"
          memory: 1G
    volumes:
      - ./Results:/fed-flow/Results
      - ./data:/fed-flow/app/dataset/data
      - ./config.py:/fed-flow/app/config/config.py



  broker:
    image: rabbitmq:3-management
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq
      RABBITMQ_MAX_MESSAGE_SIZE: 536870912
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "ping" ]
      interval: 30s
      timeout: 30s
      retries: 3

volumes:
  rabbitmq_data:

